### PR TITLE
Add: (matrix-client-sync)

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi Damien,

Thanks for sending this in.  A few notes:

* This should probably be an interactive command.
*  This is probably a good thing to have, however if the user uses it unnecessarily, it will cause multiple, simultaneous syncs for the same session.  I don't think that would necessarily break anything, as we do try to deduplicate events on the back and front ends, but it's probably not a good idea.  So I think it would be good if there were some kind of check to avoid extra sync processes.  That's what the `matrix-session` class's `pending-syncs` slot is for, although I don't think we make very good use of it right now.
* Ideally this would all be completely unnecessary, as we'd have a watchdog timer that would restart syncing when necessary.  I started work on one in this branch: https://github.com/jgkamat/matrix-client-el/tree/watchdog  It's been a few days since I worked on it last.  As I recall, there were two issues I encountered:
  * While testing, it's necessary to have the syncs get stuck so the watchdog can have a chance to fix it, but since I still don't know exactly why they get stuck, I can't cause it on-demand, so I end up leaving it running in the background, hoping to catch one (it's like fishing, haha0.
  * There seem to be some issues regarding network process buffers, killing processes, deleting the buffers, etc.  I'm not sure if it's a bug in my code or something else, but I don't have a firm grasp of how Emacs network processes work, so it may indeed be my fault.
    * Incidentally, and perhaps related to this, is a very mysterious issue I've noticed in `magit-todos` for a while: somehow some code in Emacs seems to mix up the `matrix-client` network processes and the `magit-todos` scanner processes.  I notice this sometimes when I see the Matrix syncing stop, and I look in `list-processes` and see a long list of stuck `matrix.org` processes.  Usually I can delete them all by pressing `d`, and then syncing will resume.  But when I'm encountering this issue, every time I delete one of the `matrix.org` network processes, I get an error from `async-when-done` trying to select one of the deleted `magit-todos` scanner process buffers!  To try to fix that problem, I'm testing a `magit-todos` [branch](https://github.com/alphapapa/magit-todos/tree/copy-async-when-done) that copies `async-when-done` with a slight change.  It seems to be helping that problem.  So I'm not sure if these issues are related.  It's very strange.

Well, that's all probably more than you wanted to know.  But if you can lend any of your expertise to solving these problems, I'd appreciate it, as they've been dogging me for a while.

Thanks.

**Comment by DamienCassou** [comment]
@alphapapa I took care of adding the missing `(interactive)`. Sorry.

I don't plan to invest much time in improving matrix-client-el for now, I already have a lot on my plate. But I wish you the best.

**Comment by alphapapa** [comment]
I think I will hold off on merging this for a little while, until I see whether the watchdog takes care of it.  I'd like to avoid adding the command unless it's still needed.  Thanks for your help getting all this fixed.

**Comment by alphapapa** [comment]
Since the watchdog seems to be working well for both of us, I'll close this now.  Hopefully it will never be necessary to add it.  :)  Thanks.

**Pull request closed without merging**
